config/routes.rb
Courier::Application.routes.draw do
  ActiveAdmin.routes(self)

  get "/" => "home#index"
  get "/members" => "home#members"

  resources :clients
  resources :jobs do
    collection do
      get "summary"
    end
    member do
      get "cancel"
      get "summary"
    end
    resources :drops
  end

  resources :location_update
  resources :locations do
    collection do
      match "search"
    end
  end

  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/drop.rb
class Drop < ActiveRecord::Base
  belongs_to :job
  belongs_to :location
  has_one :user, :through => :job

  attr_accessible :authorized_by, :authorized_on, :job_id, :location_id

  validates :location_id, :presence => true

  before_update :update_authorized_on

  def to_s
    "Drop at #{location.name}" unless location.nil? or location.name.nil?
  end

  private
  # update authorized_on when authorized_by is updated
  def update_authorized_on
    if @changed_attributes.include? "authorized_by"
      self.authorized_on = Time.now
    end
  end
end

app/controllers/drops_controller.rb
class DropsController < InheritedResources::Base
  belongs_to :job
end

app/views/drops/_form.haml
= simple_form_for(@drop, :html => { :class => "form-horizontal" } ) do |f|
  .form-inputs
    = f.association :location

  .form-actions
    = f.button :submit, :class => "btn btn-primary"
    or
    = link_to "Cancel", :back

app/views/drops/edit.haml
%h1 Edit Drop

= render 'form'

= link_to 'Show', @drop
\|
= link_to 'Back', drops_path

app/views/drops/index.haml
%h1 Drops
%a{ :href => new_drop_path }
  %i.icon-plus
  New Drop

%table.table.table-striped
  %thead
    %tr
      %td Client
      %td Address
  %tbody
    - @drops.each do |drop|
      %tr
        %td= drop.job.client.name
        %td= drop.location.address unless drop.location.nil?

app/views/drops/new.haml
%h1 New Drop

= render 'form'

= link_to 'Back', drop_path

app/views/drops/show.haml
%h2 Drop

Client: 
= @drop.job.client.name

%address
  = @drop.location.address

= link_to 'Edit', edit_drop_path(@drop)
\|
= link_to 'Back', drops_path