config/routes.rb
Courier::Application.routes.draw do
  ActiveAdmin.routes(self)

  get "/" => "home#index"
  get "/members" => "home#members"

  resources :clients
  resources :jobs do
    collection do
      get "summary"
    end
    member do
      get "cancel"
      get "summary"
    end
    resources :drops
  end

  resources :location_update
  resources :locations do
    collection do
      match "search"
    end
  end

  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/job.rb
class Job < ActiveRecord::Base
  resourcify

  attr_accessible :notes, :user, :client_id, :user_id, :drops_attributes, :pieces, :weight

  belongs_to :client
  belongs_to :user
  has_many :drops

  validates :client_id, :presence => true
  accepts_nested_attributes_for :drops, :allow_destroy => true

  def status
    if self.drops.count >= 2
      if self.drops.first.authorized_by.nil?
        return :"awaiting pickup"
      elsif self.drops.last.authorized_by.nil?
        return :"in transit"
      else
        return :completed
      end
    end
    return :processing
  end

  def courier_summary
    {
      :id => self.id,
      :courier_id => self.user_id,
      :client => self.client,
      :drops => self.drops.collect do |drop|
        drop.location.summary
      end
    }
  end
end

app/controllers/jobs_controller.rb
class JobsController < InheritedResources::Base
  layout :layout

  def layout
    (["show", "index"].include? action_name) ? "nocontainer" : "application"
  end

  def index
    super do |format|
      format.json do
        locations = {}
        render json: {
          :jobs => Job.find(:all, :include => [:drops, {drops: :location}]).collect{ |job|
            {
              :id => job.id,
              :courier_id => job.user_id,
              :drops => job.drops.collect do |drop|
                locations[drop.location_id] = drop.location.summary
                drop.location_id
              end
            }
          },
          :locations => locations
        }
      end
    end
  end

  def new
    super do |format|
      format.html {
        2.times { @job.drops.build }
      }
    end
  end

  def summary
    if params.include? :id then
      render json: Job.find(params[:id], :include => [:client, :drops, {drops: :location}]).courier_summary
    else
      render json: Job.find(:all, :include => [:client, :drops, {drops: :location}]).collect(&:courier_summary)
    end
  end

  def create
    @job = Job.new params[:job]
    @job.client_id = current_user.client_id if params[:job][:client_id].nil?
    create!
  end

  def cancel
    #TODO cancel job, send email
  end
end

app/views/jobs/_form.haml
= simple_form_for @job do |f|
  .row-fluid
    .form-horizontal
      .form-inputs
        = f.association :client if current_user.has_role? :admin
        = f.association :user, :label => "Courier" if current_user.has_role? :admin
        - labels = ["Pickup Location", "Dropoff Location"]
        .controls
          .help-block
            Location not listed?
            = link_to "Add it", new_location_path
        - i = 0
        = f.simple_fields_for :drops do |drop_form|
          = drop_form.association :location, :label => labels[i]
          - i += 1
        = f.input :notes, :as => :text

      .form-actions
        = f.button :submit, :class => "btn btn-primary"
        or
        = link_to "Cancel", :back

app/views/jobs/edit.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.haml
.navbar.navbar-static-top.navbar-transparent
  .navbar-inner
    .container
      .brand Jobs
      = link_to "Add Job", new_job_path, :class => "btn"

.container
  %table.table.table-striped
    %thead
      %tr
        %th Status
        %th Courier
        %th Client
        %th Pickup
        %th Dropoff
    %tbody
      - unless @jobs.nil?
        - @jobs.each do |job|
          %tr
            %td= link_to job.status.to_s.capitalize, job
            %td
              - if job.user.nil?
                .form-inline
                  = simple_form_for job, :defaults => { :label_html => { :class => 'hide' }, :class => "form-inline" } do |f|
                    = f.association :user, :label => nil
                    = f.button :submit, :class => "btn"
              - else
                = job.user.name
            %td= job.client.name unless job.client.nil?
            %td= job.drops.first.location.address unless job.drops.first.nil?
            %td= job.drops.last.location.address unless job.drops.last.nil?

app/views/jobs/new.haml
%h1 New job

= render 'form'

app/views/jobs/show.haml
- content_for :head do
  = javascript_include_tag "jobs/show"

.container
  .row
    .span4
      #map
        %span.loading Loading map

    .span8
      .navbar.navbar-static-top.navbar-transparent
        .navbar-inner
          .brand Delivery Details
          .btn-group.pull-right
            = link_to 'Edit', edit_job_path(@job), :class => "btn" if current_user.has_role? :admin
            = link_to 'Cancel Delivery', cancel_job_path(@job), :class => "btn btn-danger" if @job.status == :"awaiting pickup"

      %table.table
        %thead
          %tr
            %td.span1
            - if current_user.has_role? :admin
              %th.span5 Status
              %th.span3 Courier
              %th.span3 Client
            - else
              %th.span11 Status
        %tbody
          %tr
            %th
            %td
              = @job.status.to_s.capitalize
            - if current_user.has_role? :admin
              %td
                = @job.user.nil? ? "&mdash;".html_safe : "#{link_to @job.user.name, @job.user}".html_safe
              %td
                = @job.client.nil? ? "&mdash;".html_safe : "#{link_to @job.client.name, @job.client}".html_safe

      %table.table.table-striped
        %thead
          %tr
            %td.span1
            %th.span5 Location
            %th.span3 Completed at
            %th.span3 Authorized by
        %tbody
          - i = 0
          - @job.drops.each do |drop|
            - #TODO show when a drop has been completed
            %tr.drop-row{:"data-lat" => drop.location.lat, :"data-lng" => drop.location.lng}
              %td.icon
                %img{:src => marker_icon(i)}
              %td= drop.location.display_name
              %td= drop.authorized_on || "&mdash;".html_safe
              %td= drop.authorized_by || "&mdash;".html_safe
            - i += 1