config/routes.rb
Courier::Application.routes.draw do
  ActiveAdmin.routes(self)

  get "/" => "home#index"
  get "/members" => "home#members"

  resources :clients
  resources :jobs do
    collection do
      get "summary"
    end
    member do
      get "cancel"
      get "summary"
    end
    resources :drops
  end

  resources :location_update
  resources :locations do
    collection do
      match "search"
    end
  end

  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name, :notes

  has_many :jobs

  validates :name, :presence => true
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
  layout :layout

  def layout
    (["index"].include? action_name) ? "nocontainer" : "application"
  end

  def index
    super do |format|
      format.html do
        @clients = Client.page(params[:page])
      end
    end
  end
end

app/views/clients/_form.haml
= simple_form_for(@client, :html => { :class => "form-horizontal" } ) do |f|

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit, :class => "btn btn-primary"

app/views/clients/edit.haml
%h1
  = @client.name

= render 'form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path

app/views/clients/index.haml
.navbar.navbar-static-top
  .navbar-inner
    .container
      .brand Clients
      = link_to "New Client", new_client_path, :class => "btn"
      = render "layouts/searchform"

.container
  - if @clients.count > 0
    %table.table.table-striped
      %thead
        %tr
          %th Name
      %tbody
        - @clients.each do |client|
          %tr
            %td= link_to client.name, client
  - else
    .alert
      %p No Clients

  = paginate @clients

app/views/clients/new.haml
%h1 New Client

= render 'form'

= link_to 'Back', clients_path

app/views/clients/show.haml
%h2
  = @client.name
  %small= link_to 'Edit', edit_client_path(@client)

%h3
  Recent Jobs
  %small
    %a{ :href => new_job_path }
      Add Job

- if @client.jobs.count > 0
  %table.table.table-striped
    %thead
      %tr
        %td Courier
    %tbody
      - @client.jobs.each do |job|
        %tr
          %td
            - if job.user.nil?
              Unassigned
            - else
              = job.user.name
          %td
            = link_to 'Edit', edit_job_path(job)
            = link_to 'Delete', job, :confirm => 'Are you sure?', :method => :delete