config/routes.rb
Courier::Application.routes.draw do
  ActiveAdmin.routes(self)

  get "/" => "home#index"
  get "/members" => "home#members"

  resources :clients
  resources :jobs do
    collection do
      get "summary"
    end
    member do
      get "cancel"
      get "summary"
    end
    resources :drops
  end

  resources :location_update
  resources :locations do
    collection do
      match "search"
    end
  end

  devise_for :users
  resources :users, :only => [:show, :index]
end

app/views/layouts/_header.haml
%header.navbar.navbar-inverse.navbar-fixed-top
  %nav.navbar-inner
    .container
      = link_to APP_TITLE, "/", :class => 'brand'
      - if user_signed_in?
        %ul.nav
          - if current_user.has_role? :admin
            %li= link_to "Jobs", jobs_path
            %li= link_to "Clients", clients_path
            %li= link_to "Locations", locations_path
          - else
            %li= link_to "View Deliveries", '/'
            %li= link_to "Request Delivery", new_job_path
            %li= link_to "Address Book", locations_path

      %ul.nav.pull-right
        - if user_signed_in?
          %li
            = link_to('Settings', edit_user_registration_path)
          %li
            = link_to('Logout', destroy_user_session_path, :method=>'delete')
        - else
          %li
            = link_to('Sign up', new_user_registration_path)
          %li
            = link_to('Login', new_user_session_path)

app/views/layouts/_messages.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_searchform.haml
%form.form-search.navbar-form.pull-right
  .input-append
    %input.span3.search-query{:type => :text, :name => :q, :value => params[:q]}
    %button.btn{:type => :submit} Search

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %script{ :src => "https://maps.googleapis.com/maps/api/js?sensor=false", :type => "text/javascript" }
    %title= content_for?(:title) ? yield(:title) : APP_TITLE
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{ :class => [controller_name, "#{controller_name}-#{action_name}", @body_classes] }
    = render 'layouts/header'
    #main{:role => "main"}
      .container
        .flash
          = render 'layouts/messages'
        = yield

app/views/layouts/map.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : APP_TITLE
    %script{ :src => "https://maps.googleapis.com/maps/api/js?sensor=false", :type => "text/javascript" }
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{ :class => [controller_name, "#{controller_name}-#{action_name}", current_user.nil? ? "" : "loggedin"] }
    = render 'layouts/header'
    = yield

app/views/layouts/nocontainer.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %script{ :src => "https://maps.googleapis.com/maps/api/js?sensor=false", :type => "text/javascript" }
    %title= content_for?(:title) ? yield(:title) : APP_TITLE
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{ :class => [controller_name, "#{controller_name}-#{action_name}", @body_classes] }
    = render 'layouts/header'
    #main{:role => "main"}
      .flash
        = render 'layouts/messages'
      = yield